app:
  scraper:
    url: http://localhost:8666
    novasoft:
      conexion: '%env(lowercase:EMPRESA)%'
    ael:
      user: '%env(empresa:SCRAPER_AEL_USER)%'
      password: '%env(empresa:SCRAPER_AEL_PASSWORD)%'
      empleador: '%env(lowercase:EMPRESA)%'

  sel_routes:
      ignore: [
        'pta_index', 'pta_servicios', 'pta_nosotros', 'vacante_listado', 'vacante_detalle', 'vacante_aplicar',
        'pta_noticias', 'pta_noticias_categoria', 'pta_noticia', 'pta_contacto', 'app_login',
        'evaluacion', 'evaluacion_culminar', 'evaluacion_pregunta', 'evaluacion_pregunta_diapositiva', 'evaluacion_diapositiva',
        'pta_politica', 'pta_aviso_privacidad']

  empresas:
    PTA:
      host: '%env(HOST_PTA)%'
      razon: PTA S.A.S
      nit: 860.527.350-6
      dir: Calle 72 A N° 20 A - 57
      web: www.pta.com.co
      mail: info@pta.com.co
      tel: (1) 756 98 40
      logo: build/pta/images/sel/pta-logo.png
      logo_pdf: build/pta/images/sel/pta-logo-pdf.png
      home_route: pta_index

      certificado_laboral:
        firma: build/pta/images/sel/firma-certificado-laboral.png
        firmante: FERNANDA SANCHEZ LAGUNA
        firmante_cargo: Directora de Servicio al Cliente
        firmante_contacto: PBX 756 98 40 Ext. 110-106-136

      ssrs_db:
        PTA: ~

      emails:
        contacto:
          Dudas, comentarios:
            - servicioalcliente@pta.com.co
          Solicitud servicios:
            - fernanda.sanchez@pta.com.co
            - angela.pineda@pta.com.co
          Aportes seguridad social:
            - analista.seguridad@pta.com.co
          Nomina y prestaciones sociales:
            - nomina@pta.com.co
            - analista.seguridad@pta.com.co
          Pagaduría:
            - analista.contable@pta.com.co
          Quejas y reclamos:
            - servicioalcliente@pta.com.co
            - bienestar@pta.com.co
          Salud ocupacional:
            - salud.ocupacional@pta.com.co
          Selección y reclutamiento:
            - paula.hoyos@pta.com.co
          Servicio al cliente:
            - servicioalcliente@pta.com.co

      scraper:
        novasoft:
          browser: 'novasoft.cguerrero'

    SERVILABOR:
      host: '%env(HOST_SERVILABOR)%'
      razon: SERVILABOR S.A.S
      nit: 800.154.576-3
      dir: 'Cra 14 # 76-39 Of 102'
      web: www.servilabor.com.co
      mail: info@servilabor.com.co
      tel: 300 31 13
      logo: build/servilabor/images/sel/logo-servilabor.png
      logo_pdf: build/servilabor/images/sel/logo-servilabor-pdf.png
      home_route: servilabor_inicio

      certificado_laboral:
        firma: build/servilabor/images/sel/firma-certificado-laboral-servilabor.png
        firmante: SERGIO INVERNON RAMOS
        firmante_cargo: Gerente General
        firmante_contacto: PBX 300 31 13

      emails:
        contacto: '%env(empresa:EMAILS_CONTACTO)%'

      ssrs_db:
        SERVILABOR: ~
        UNIVERSAL:
          convenios: false
          reportes:
            empleado: Nom933
        EMPLEADOS_SOS:
          convenios: false
          reportes:
            empleado: Nom933

      companias:
        UNIVERSAL:
          razon: UNIVERSAL MUSIC COLOMBIA S.A.S.
          nit: 800.246.963-6
          dir: CALLE 103 Nº 21-60
          tel: 4140077
          web:
          logo_pdf: build/servilabor/images/sel/logo-universal.png

      scraper:
        novasoft:
          browser: 'novasoft'

  # TODO borar
  hv_wizard_routes:
    basicos:
      route: registro_datos_basicos
      titulo: Básicos
    estudios:
      route: registro_estudios
      titulo: Estudios
    experiencia:
      route: registro_experiencia
      titulo: Experiencia
    referencias:
      route: registro_referencias
      titulo: Referencias
    familiares:
      route: registro_familiares
      titulo: Familiares
    cuenta:
      route: registro_cuenta
      titulo: Cuenta