app:
  scraper:
    url: http://localhost:8666

  empresas:
    PTA:
      host: '%env(HOST_PTA)%'
      razon: PTA S.A.S
      nit: 860.527.350-6
      dir: Calle 72 A N° 20 A - 57
      web: www.pta.com.co
      mail: info@pta.com.co
      tel: (1) 756 98 40
      logo: /img/sel/pta-logo.png
      logo_pdf: /img/sel/pta-logo-pdf.png
      home_route: pta_index

      certificado_laboral:
        firma: /img/sel/firma-certificado-laboral.png
        firmante: FERNANDA SANCHEZ LAGUNA
        firmante_cargo: Directora de Servicio al Cliente
        firmante_contacto: PBX 756 98 40 Ext. 110-106-136

      ssrs_db:
        PTA: ~

      emails:
        contacto:
          Dudas, comentarios:
            - servicioalcliente@pta.com.co
          Aportes seguridad social:
            - analista.seguridad@pta.com.co
          Nomina y prestaciones sociales:
            - nomina@pta.com.co
            - analista.seguridad@pta.com.co
          Pagaduría:
            - martha.duarte@pta.com.co
          Quejas y reclamos:
            - servicioalcliente@pta.com.co
            - bienestar@pta.com.co
          Salud ocupacional:
            - salud.ocupacional@pta.com.co
          Selección y reclutamiento:
            - paula.hoyos@pta.com.co
          Servicio al cliente:
            - servicioalcliente@pta.com.co
              
#      hv_wizard_routes:
#        basicos:
#          route: registro_datos_basicos
#          titulo: Básicos
#        estudios:
#          route: registro_estudios
#          titulo: Estudios
#        experiencia:
#          route: registro_experiencia
#          titulo: Experiencia
#        referencias:
#          route: registro_referencias
#          titulo: Referencias
#        familiares:
#          route: registro_familiares
#          titulo: Familiares
#        cuenta:
#          route: registro_cuenta
#          titulo: Cuenta

      scraper:
        ael:
          user: '%env(empresa:SCRAPER_AEL_USER)%'
          password: '%env(empresa:SCRAPER_AEL_PASSWORD)%'
          empleador: pta

    SERVILABOR:
      host: '%env(HOST_SERVILABOR)%'
      razon: SERVILABOR S.A.S
      nit: 800.154.576-3
      dir: 'Cra 14 # 76-39 Of 102'
      web: www.servilabor.com.co
      mail: info@servilabor.com.co
      tel: 300 31 13
      logo: /img/sel/logo-servilabor.png
      logo_pdf: /img/sel/logo-servilabor-pdf.png
      home_route: servilabor_inicio

      certificado_laboral:
        firma: /img/sel/firma-certificado-laboral-servilabor.png
        firmante: SERGIO INVERNON RAMOS
        firmante_cargo: Gerente General
        firmante_contacto: PBX 300 31 13

      emails:
        contacto: guerrerojosedario@gmail.com

      ssrs_db:
        SERVILABOR: ~
        UNIVERSAL:
          convenios: false
        EMPLEADOS_SOS:
          convenios: false

      scraper:
        ael:
          user: '%env(empresa:SCRAPER_AEL_USER)%'
          password: '%env(empresa:SCRAPER_AEL_PASSWORD)%'
          empleador: servilabor
