app:
  empresas:
    PTA:
      oficinas:
        bogota:
          ciudad: Bogotá
          direccion: Calle 72 A N° 20 A - 57
          telefono: (1) 7569840
          email: servicioalcliente@pta.com.co
          latitude: 4.66122
          longitude: -74.06336
          principal: true

        barranquilla:
          ciudad: Barranquilla
          direccion: Calle 77B No. 57-103, Piso 10, Oficina 1001, Edificio Green Towers
          telefono: (5) 316 23 84
          email: barranquilla@pta.com.co
          latitude: 11.0049129
          longitude: -74.8151875

        bucaramanga:
          ciudad: Bucaramanga
          direccion: ~
          telefono: 316 244 06 19
          email: bucaramanga@pta.com.co
          latitude: 0
          longitude: 0

        cali:
          ciudad: Cali
          direccion: Calle 22 Norte Nº 4 N - 56    Of. 204 (Edf. Vanesa)
          telefono: 320 809 14 70
          email: agenciacali@pta.com.co
          latitude: 3.462535
          longitude: -76.527968

        duitama:
          ciudad: Duitama
          direccion: Calle 16 N° 14-41Of. 1008 (Centro Empresarial Palma Real)
          telefono: 310 306 22 34
          email: duitama@pta.com.co
          latitude: 5.82880
          longitude: -73.03401

        medellin:
          ciudad: Medellín
          direccion: 'Carrera 43A # 11A-44 Piso, 2'
          telefono: (4) 2 04 02 99
          email: ptamedellin@pta.com.co
          latitude: 6.2124013
          longitude: -75.5718482