app:
  empresas:
    PTA:
      documentos_laborales:
        protocolo-de-bioseguridad-1513:
          title: PROTOCOLO DE BIOSEGURIDAD 1513
          date: 2020-09-02
          category: COVID-19
        prevencion-covid-medidas-generales:
          title: Prevención covid medidas generales
          date: 2020-05-22
          category: COVID-19
        prevencion-covid-lavado-manos:
          title: Prevención covid lavado de manos
          date: 2020-05-22
          category: COVID-19
        prevencion-covid-higiene-respiratoria:
          title: Prevención covid higiene respiratoria
          date: 2020-05-22
          category: COVID-19
        prevencion-covid-alimentacion:
          title: Prevención covid alimentación
          date: 2020-05-22
          category: COVID-19
        prevencion-contencion-mitigacion-del-covid-19-adultos-mayores:
          title: Prevención, contención y mitigación del Covid-19 en personas adultas mayores
          date: 2020-05-22
          category: COVID-19
        prevencion-covid-psicolaboral:
          title: Prevención covid psicolaboral
          date: 2020-05-22
          category: COVID-19
        prevencion-covid-adultos-mayores:
          title: Prevención covid adultos mayores
          date: 2020-05-22
          category: COVID-19
        personas-con-discapacidad-covid-19:
          title: Personas con discapacidad covid 19
          date: 2020-05-22
          category: COVID-19
        recomendaciones-agua:
          title: Recomendaciones con el agua para el consumo humano
          date: 2020-05-22
          category: COVID-19
        recomendaciones-propiedad-horizontal:
          title: Recomendaciones para propiedad horizontal
          date: 2020-05-22
          category: COVID-19

        requisitos-incapacidades:
          date: 2019-05-13
          title: Requisitos incapacidades
        que-hacer-despues-de-atencion-urgencias-por-accidente-de-trabajo:
          date: 2019-03-13
          title: '¿Qué debo hacer después de la atención de Urgencias por un Accidente de Trabajo?'
        politica-de-tratamiento-de-datos-personales:
          date: 2018-01-01
          title: Política de Tratamiento de Datos Personales
          pdf: POLITICA-TRATAMIENTO-DATOS-PERSONALES
        circular-interna:
          date: 2017-12-15
          title: Circular interna PTA SAS
          pdf: CIRCULAR-INTERNA
        reglamento-interno:
          date: 2017-12-15
          title: Reglamento interno PTA SAS
          pdf: RIT-2017
        politica-para-la-prevencion-del-consumo-de-sustancias-psicoactivas:
          date: 2016-12-14
          title: Política prevención consumo sustancias psicoactivas
        reglamento-de-higiene-y-seguridad-industrial:
          date: 2016-12-14
          title: Reglamento de higiene y seguridad industrial
        politica-de-seguridad-y-salud-en-el-trabajo:
          date: 2016-12-14
          title: Política de seguridad y salud en el trabajo

    SERVILABOR:
      documentos_laborales:
        politica-sst:
          date: 2020-02-14
          title: Politica de seguridad y salud en el trabajo
          pdf: SST-PO-01-4-POLITICA-SGSST
        politica-para-la-prevencion-del-consumo-de-sustancias-psicoactivas:
          date: 2020-02-14
          title: Política prevención consumo de sustancias psicoactivas
          pdf: SST-PO-02-05-POLITICA-PREVENCION-CONSUMO-SUSTANCIAS-PSICOACTIVAS
        politica-de-seguridad-vial:
          date: 2020-02-14
          title: Política de seguridad vial
          pdf: SST-PO-03-03-POLITICA-SEGURIDAD-VIAL
        reglamento-de-higiene-y-seguridad-industrial:
          date: 2019-09-24
          title: Reglamento de higiene y seguridad industrial
          pdf: REGLAMENTO-DE-HIGIENE-Y-SEGURIDAD-INDUSTRIAL
        reglamento-interno-de-trabajo:
          date: 2015-11-06
          title: Reglamento interno de trabajo
          pdf: REGLAMENTO-INTERNO-DE-TRABAJO
