framework:
    assets:
        #json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
        json_manifest_path: '%kernel.project_dir%/public/build/%env(lowercase:EMPRESA)%/manifest.json'
