parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: '5.5.27'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_general_ci
                url: '%env(resolve:DB_URL)%'

            se:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: '5.5.27'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_general_ci
                url: '%env(migrationdb:DATABASE_SE_URL)%'

            se_aspirante:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: '5.5.27'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_general_ci
                url: '%env(resolve:DATABASE_SE_ASPIRANTE_URL)%'

            se_vacantes:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: '5.5.27'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_general_ci
                url: '%env(resolve:DATABASE_SE_VACANTES_URL)%'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                hydrators:
                    FETCH_COLUMN: App\Hydrators\FetchColumnHydrator
                    FETCH_KEY_PAIR: App\Hydrators\FetchKeyPairHydrator

                dql:
                    numeric_functions:
                        rand: DoctrineExtensions\Query\Mysql\Rand
