parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: '5.5.27'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_general_ci
                url: '%env(resolve:DB_URL)%'
                schema_filter: '~^(?!messenger_messages)~'

            halcon:
                driver: 'pdo_mysql'
                server_version: '5.5.27'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_general_ci
                url: '%env(empresa:DATABASE_HALCON_URL)%'

            se:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: '5.5.27'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_general_ci
                url: '%env(migrationdb:DATABASE_SE_URL)%'

            se_aspirante:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: '5.5.27'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_general_ci
                url: '%env(resolve:DATABASE_SE_ASPIRANTE_URL)%'

            se_vacantes:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: '5.5.27'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_general_ci
                url: '%env(resolve:DATABASE_SE_VACANTES_URL)%'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                connection: default
                mappings:
                    Autoliquidacion:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Autoliquidacion'
                        prefix: 'App\Entity\Autoliquidacion'
                        alias: Autoliquidacion
                    Evaluacion:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Evaluacion'
                        prefix: 'App\Entity\Evaluacion'
                        alias: Evaluacion
                    Hv:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Hv'
                        prefix: 'App\Entity\Hv'
                        alias: Hv
                    AppBundle:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
                    Novasoft:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Novasoft'
                        prefix: 'App\Entity\Novasoft'
                        alias: Novasoft
                    ServicioEmpleados:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/ServicioEmpleados'
                        prefix: 'App\Entity\ServicioEmpleados'
                        alias: ServicioEmpleados
                    Scraper:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Scraper'
                        prefix: 'App\Entity\Scraper'
                        alias: Scraper
                    Vacante:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Vacante'
                        prefix: 'App\Entity\Vacante'
                        alias: Vacante
                hydrators:
                    FETCH_COLUMN: App\Service\Doctrine\Hydrators\FetchColumnHydrator
                    FETCH_KEY_PAIR: App\Service\Doctrine\Hydrators\FetchKeyPairHydrator

                dql:
                    numeric_functions:
                        rand: DoctrineExtensions\Query\Mysql\Rand

            halcon:
                connection: halcon
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Halcon:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Halcon'
                        prefix: 'App\Entity\Halcon'
                        alias: Halcon

                dql:
                    string_functions:
                        ifnull: DoctrineExtensions\Query\Mysql\IfNull
                    datetime_functions:
                        date_format: DoctrineExtensions\Query\Mysql\DateFormat


