monolog:
    channels:
        - sel
        - napi_import_empleado
        - scraper
        #deprecated
        - ni_empleado
        - ni_nomina
        - ni_convenio
        - se_report_cache_import
        - se_report_cache_delete
        - messenger_audit

    handlers:
        napi_import_empleado:
            type: stream
            path: "%kernel.logs_dir%/napi/import/empleado.log"
            level: debug
            channels: napi_import_empleado
        #deprecated
        ni_empleado:
            type: stream
            path: "%kernel.logs_dir%/ni/empleado.log"
            level: debug
            channels: ni_empleado
        ni_nomina:
            type: stream
            path: "%kernel.logs_dir%/ni/nomina.log"
            level: debug
            channels: ni_nomina
        ni_convenio:
            type: stream
            path: "%kernel.logs_dir%/ni/convenio.log"
            level: debug
            channels: ni_convenio

        se_report_cache:
            type: stream
            path: "%kernel.logs_dir%/se/report-cache.log"
            level: debug
            channels:
                - se_report_cache_import
                - se_report_cache_delete

        messenger:
            type: stream
            path: "%kernel.logs_dir%/messenger.log"
            level: debug
            channels: ["messenger_audit"]

