monolog:
    channels:
        - sel
        - scraper
        - ni_empleado
        - ni_nomina
        - ni_convenio
        - messenger_audit
    handlers:
        ni_empleado:
            type: stream
            path: "%kernel.logs_dir%/ni/empleado.log"
            level: debug
            channels: ni_empleado
        ni_nomina:
            type: stream
            path: "%kernel.logs_dir%/ni/nomina.log"
            level: debug
            channels: ni_nomina
        ni_convenio:
            type: stream
            path: "%kernel.logs_dir%/ni/convenio.log"
            level: debug
            channels: ni_convenio

        messenger:
            type: stream
            path: "%kernel.logs_dir%/messenger.log"
            level: debug
            channels: ["messenger_audit"]

