# Read the documentation: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/index.md
oneup_uploader:
    mappings:
        # This is a mapping example, remove it and create your own mappings.
        archivo:
            frontend: dropzone # or any uploader you use in the frontend
            storage:
                type: flysystem
                filesystem: oneup_flysystem.sel_filesystem
            namer: App\Uploader\Namer\ArchivoNamer
