# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        public_uploads_adapter:
            local:
                directory: '%kernel.cache_dir%/flysystem'
        private_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/%private_uploads_dir_name%'

        se_reportes:
            local:
                directory: '%kernel.cache_dir%/se/reportes/'

        migration_autoliquidacion_adapter:
            local:
                directory: '%env(empresa:MIGRATION_PATH_AUTOLIQUIDACIONES)%'
        migration_evaluacion_template:
            local:
                directory: '%env(MIGRATION_EVALUACION_TEMPLATES)%'
        migration_evaluacion_template_target:
            local:
                directory: '%kernel.project_dir%/templates/%env(lowercase:EMPRESA)%/app/evaluacion'
    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adapter
        private_uploads_filesystem:
            adapter: private_uploads_adapter

        se_reportes:
            adapter: se_reportes

        migration_autoliquidacion_adapter:
            adapter: migration_autoliquidacion_adapter
        migration_evaluacion_template:
            adapter: migration_evaluacion_template
        migration_evaluacion_template_target:
            adapter: migration_evaluacion_template_target
