# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        public_uploads_adapter:
            local:
                directory: '%kernel.cache_dir%/flysystem'
        private_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/%private_uploads_dir_name%'
        se_report:
            local:
                directory: '%kernel.project_dir%/%private_uploads_dir_name%/se/report'

        #TODO deprecated borrar
        novasoft_report:
            local:
                directory: '%kernel.project_dir%/%private_uploads_dir_name%/novasoft/report'

        migration_autoliquidacion_adapter:
            local:
                directory: '%env(empresa:MIGRATION_PATH_AUTOLIQUIDACIONES)%'
        migration_hv_adjunto_adapter:
            local:
                directory: '%env(MIGRATION_HV_ADJUNTO)%'
        migration_evaluacion_template:
            local:
                directory: '%env(MIGRATION_EVALUACION_TEMPLATES)%'
        migration_evaluacion_template_target:
            local:
                directory: '%kernel.project_dir%/templates/%env(lowercase:EMPRESA)%/app/evaluacion'
    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adapter
        private_uploads_filesystem:
            adapter: private_uploads_adapter
        se_report:
            adapter: se_report

        #TODO deprecated borrar
        novasoft_report:
            adapter: novasoft_report

        migration_autoliquidacion_adapter:
            adapter: migration_autoliquidacion_adapter
        migration_evaluacion_template:
            adapter: migration_evaluacion_template
        migration_evaluacion_template_target:
            adapter: migration_evaluacion_template_target
        migration_hv_adjunto_filesystem:
            adapter: migration_hv_adjunto_adapter
