twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/evaluacion_types.html.twig'
        - 'bootstrap_4_layout.html.twig'
        - 'form/sel_layout.html.twig'
    globals:
        configuracion: '@App\Service\Configuracion\Configuracion'

    paths:
        - '%kernel.project_dir%/templates/%env(EMPRESA)%/app'