---
- name: Clear build folder
  shell: "rm -rf ../public/build/*"
  args:
    warn: no

- name: Build webpack
  command: "yarn build"
  environment:
    EMPRESA: "{{ empresa }}"

- name: Archive webpack
  archive:
    path: "{{ playbook_dir }}/../public/build"
    dest: "{{ playbook_dir }}/../public/build.tgz"

#- name: Archive webpack
#  shell: "tar -czf ../public/build.tar.gz ../public/build"
#  args:
#    warn: no
#
#- name: Scp webpack
#  command: "scp ../public/build.tar.gz {{ empresa }}:."
#  args:
#    warn: no