---
- name: Set up infrastructure related params
  template:
      src: "{{ playbook_dir }}/templates/.env.local2"
      dest: "{{ ansistrano_release_path.stdout }}/.env.local"

- name: Set up htaccess
  template:
      src: "{{ playbook_dir }}/templates/.htaccess"
      dest: "{{ release_public_path }}/.htaccess"

- name: Modify console
  replace:
      path: "{{ ansistrano_release_path.stdout }}/bin/console"
      regexp: '^(#!/usr/bin/env) php'
      replace: '\1 {{ php_exec }}'

- name: Modify messenger console
  replace:
      path: "{{ ansistrano_release_path.stdout }}/bin/messenger"
      regexp: '^(#!/usr/bin/env) php'
      replace: '\1 {{ php_exec }}'

- name: Install composer deps
  command: "{{ php_exec }} {{ composer }} install --no-dev"
  args:
      chdir: "{{ ansistrano_release_path.stdout }}"

#- name: Create DB if not exists
#  command: ".{{ release_console_path }} doctrine:database:create --if-not-exists --env=prod"
#  args:
#      chdir: "/"

- name: Run migrations
  command: ".{{ release_console_path }} doctrine:migrations:migrate --no-interaction --env=prod"
  args:
      chdir: "/"

- name: Setup directory permissions for var/
  file:
      path: "{{ release_var_path }}"
      state: directory
      mode: 0775
      recurse: true
      follow: true

- name: Clear the cache
  command: ".{{ release_console_path }} cache:clear --env=prod"
  args:
      chdir: "/"