---
# https://stackoverflow.com/a/50875170/1524538
- name: Install node dependencies
  shell: |
    scl enable devtoolset-7 -- yarn install
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"

- name: Install webpack encore assets
  command: yarn build
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"