---
- name: Install node dependencies
  yarn:
    path: "{{ ansistrano_release_path.stdout }}"

#- name: Install node dependencies
#  command: yarn install
#  args:
#    chdir: "{{ ansistrano_release_path.stdout }}"

- name: Install webpack encore assets
  command: yarn build
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"


#- name: Extract Webpack build
#  unarchive:
#    src: "{{ playbook_dir }}/../public/build.tgz"
#    dest: "{{ release_public_path }}"
#    owner: "{{ owner }}"
#    group: "{{ group }}"
