---
- name: Set up infrastructure related params
  template:
      src: "{{ playbook_dir }}/templates/.env.local"
      dest: "{{ ansistrano_release_path.stdout }}/.env.local"

- name: Set up htaccess
  template:
      src: "{{ playbook_dir }}/templates/.htaccess"
      dest: "{{ release_public_path }}/.htaccess"

- name: Install composer deps
  composer:
      command: install
      working_dir: "{{ ansistrano_release_path.stdout }}"

- name: Extract Webpack build
  unarchive:
    src: "{{ playbook_dir }}/../public/build.tgz"
    dest: "{{ release_public_path }}"
    owner: ptaweb
    group: ptaweb

#- name: Change file ownership, group and permissions
#  file:
#      path: "{{ ansistrano_release_path.stdout }}"
#      owner: ptaweb
#      group: ptaweb
#      state: directory
#      recurse: yes

- name: Setup directory permissions for var/
  file:
      path: "{{ release_var_path }}"
      state: directory
      mode: 0775
      recurse: true

- name: Clear the cache
  command: "{{ release_console_path }} cache:clear"