---
- name: Remote symfony
  include: "{{ playbook_dir }}/include/remote-symfony.yml"

- name: Remote webpack
  include: "{{ playbook_dir }}/include/remote-webpack.yml"
  when: webpack is defined

- name: Extract images
  unarchive:
    src: "{{ playbook_dir }}/../public/img.tgz"
    dest: "{{ release_public_path }}"
    owner: ptaweb
    group: ptaweb
  when: empresa == "pta"

- name: Extract evaluacion induccion
  unarchive:
    src: "{{ playbook_dir }}/../var/uploads/evaluacion/induccion.tgz"
    dest: "{{ release_var_path }}/uploads/evaluacion/induccion"
    owner: "{{ owner }}"
    group: "{{ group }}"
  when: empresa == "servilabor"