---
- name: Set up infrastructure related params
  template:
      src: "{{ playbook_dir }}/templates/.env.local"
      dest: "{{ ansistrano_release_path.stdout }}/.env.local"

- name: Set up htaccess
  template:
      src: "{{ playbook_dir }}/templates/.htaccess"
      dest: "{{ release_public_path }}/.htaccess"

- name: Install composer deps
  composer:
      command: install
      working_dir: "{{ ansistrano_release_path.stdout }}"

- name: Create DB if not exists
  command: "{{ release_console_path }} doctrine:database:create --if-not-exists --env=prod"
    #register: create_db_output
    #changed_when: not create_db_output.stdout|search('already exists. Skipped')

- name: Run migrations
  command: "{{ release_console_path }} doctrine:migrations:migrate --no-interaction --env=prod"
    #register: run_migrations_output
    #changed_when: not run_migrations_output.stdout|search('No migrations to execute')

- name: Extract Webpack build
  unarchive:
    src: "{{ playbook_dir }}/../public/build.tgz"
    dest: "{{ release_public_path }}"
    owner: ptaweb
    group: ptaweb

#- name: Change file ownership, group and permissions
#  file:
#      path: "{{ ansistrano_release_path.stdout }}"
#      owner: ptaweb
#      group: ptaweb
#      state: directory
#      recurse: yes

- name: Setup directory permissions for var/
  file:
      path: "{{ release_var_path }}"
      state: directory
      mode: 0775
      recurse: true

- name: Clear the cache
  command: "{{ release_console_path }} cache:clear --env=prod"