---
- name: Set up infrastructure related params
  template:
      src: "{{ playbook_dir }}/templates/.env.local"
      dest: "{{ ansistrano_release_path.stdout }}/.env.local"

- name: Set up htaccess
  template:
      src: "{{ playbook_dir }}/templates/.htaccess"
      dest: "{{ release_public_path }}/.htaccess"

#- name: Install composer deps
#  command: "{{ php_exec }} {{ composer }} install --no-dev"
#  args:
#      chdir: "{{ ansistrano_release_path.stdout }}"

- name: Create DB if not exists
  command: "{{ php_exec }} {{ release_console_path }} doctrine:database:create --if-not-exists --env=prod"

- name: Run migrations
  command: "{{ php_exec }} {{ release_console_path }} doctrine:migrations:migrate --no-interaction --env=prod"

    #register: run_migrations_output
    #changed_when: not run_migrations_output.stdout|search('No migrations to execute')

#- name: Extract Webpack build
#  unarchive:
#    src: "{{ playbook_dir }}/../public/build.tar.gz"
#    dest: "{{ release_public_path }}"
#    owner: "{{ owner }}"
#    group: "{{ group }}"

#- name: Change file ownership, group and permissions
#  file:
#      path: "{{ ansistrano_release_path.stdout }}"
#      owner: ptaweb
#      group: ptaweb
#      state: directory
#      recurse: yes

- name: Setup directory permissions for var/
  file:
      path: "{{ release_var_path }}"
      state: directory
      mode: 0775
      recurse: true

- name: Clear the cache
  command: "{{ php_exec }} {{ release_console_path }} cache:clear --env=prod"