---
- name: Set up infrastructure related params
  template:
      src: "{{ playbook_dir }}/templates/.env.local"
      dest: "{{ ansistrano_release_path.stdout }}/.env.local"

- name: Install composer deps
  composer:
      command: install
      working_dir: "{{ ansistrano_release_path.stdout }}"

- name: Clear the cache
  command: "{{ release_console_path }} cache:clear"

- name: Change file ownership, group and permissions
  file:
      path: "{{ ansistrano_release_path.stdout }}"
      owner: ptaweb
      group: ptaweb
      state: directory
      recurse: yes

- name: Setup directory permissions for var/
  file:
      path: "{{ release_var_path }}"
      state: directory
      mode: 0775
      recurse: true