<?php

namespace App\MessageHandler\Novasoft\Api;

use App\Entity\Hv\Referencia;
use App\Exception\Novasoft\Api\NotFoundException;
use App\Message\Novasoft\Api\DeleteHvChildInNovasoft;
use App\Repository\Hv\HvRepository;
use App\Service\Novasoft\Api\Client\HvClient;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;

class DeleteHvChildInNovasoftHandler implements MessageHandlerInterface
{
    /**
     * @var HvClient
     */
    private $client;
    /**
     * @var HvRepository
     */
    private $hvRepo;
    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(HvClient $client, HvRepository $hvRepo, EntityManagerInterface $em)
    {
        $this->client = $client;
        $this->hvRepo = $hvRepo;
        $this->em = $em;
    }

    public function __invoke(DeleteHvChildInNovasoft $message)
    {
        $this->em->clear();
        // referencia primary key es compuesta con autogenerated que doctrine no soporta. toca manejar asi
        if($message->getChildClass() === Referencia::class) {
            if($hv = $this->hvRepo->find($message->getHvId())) {
                $this->client->deleteReferencias($hv);
                $this->client->saveReferencias($hv);
            }
        } else {
            try {
                $this->client->deleteChild($message->getNapiId(), $message->getChildClass());
            } catch (NotFoundException $e) {
                // TODO validar que si no hay mas registros del child, en novasoft tampoco hallan
            }
        }

    }
}