<?php


namespace App\MessageHandler\Novasoft\Api;


use App\Entity\Hv\HvEntity;
use App\Entity\Hv\Referencia;
use App\Exception\Novasoft\Api\NotFoundException;
use App\Message\Novasoft\Api\UpdateHvChildInNovasoft;
use App\Repository\Hv\HvRepository;
use App\Service\Novasoft\Api\Client\HvClient;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;

class UpdateHvChildInNovasoftHandler implements MessageHandlerInterface
{
    /**
     * @var HvClient
     */
    private $client;
    /**
     * @var DenormalizerInterface
     */
    private $denormalizer;
    /**
     * @var HvRepository
     */
    private $hvRepo;
    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(HvClient $client, DenormalizerInterface $denormalizer, HvRepository $hvRepo, EntityManagerInterface $em)
    {
        $this->client = $client;
        $this->denormalizer = $denormalizer;
        $this->hvRepo = $hvRepo;
        $this->em = $em;
    }

    public function __invoke(UpdateHvChildInNovasoft $message)
    {

        $this->em->clear();
        // referencia primary key es compuesta con autogenerated que doctrine no soporta. toca manejar asi
        if($message->getChildClass() === Referencia::class) {
           if($hv = $this->hvRepo->find($message->getHvId())) {
               $this->client->deleteReferencias($hv);
               $this->client->saveReferencias($hv);
           }
        } else {
            /** @var HvEntity $hvEntity */
            $hvEntity = $this->denormalizer->denormalize(
                $message->getChildNormalized(), $message->getChildClass(), null, ['groups' => ['messenger:hv-child:put', 'napi:hv-child:put']]
            );
            try {
                $this->client->putChild($hvEntity);
            } catch (NotFoundException $e) {
                $this->client->postChild($hvEntity);
            }
        }
    }
}