---
symfony_secret: '{{ vault_symfony_secret }}'
database_host: '{{ vault_database_host }}'
database_user: '{{ vault_database_user }}'
database_pass: '{{ vault_database_pass }}'
database: '{{ vault_database }}'
cache_adapter: '{{ vault_cache_adapter }}'
ssrs_user: '{{ vault_ssrs_user }}'
ssrs_pass: '{{ vault_ssrs_pass }}'
ssrs_url: '{{ vault_ssrs_url }}'
gmail_user: '{{ vault_gmail_user }}'
gmail_pass: '{{ vault_gmail_pass }}'
gmaps_key: '{{ vault_gmaps_key }}'
scraper_ael_user: '{{ vault_scraper_ael_user }}'
scraper_ael_pass: '{{ vault_scraper_ael_pass }}'
migration_user: '{{ vault_migration_user }}'
migration_dbprefx: '{{ vault_migration_dbprefix }}'