app:
    scraper:
        url: http://3.237.96.100:8666
    ael:
        url: http://3.237.96.100:8667
    empresas:
        SERVILABOR:
            php_exec: /opt/php71/bin/php

    novasoftapi:
        url: http://3.237.96.100:80