app:
    scraper:
        url: http://50.19.144.184:8666
    ael:
        url: http://50.19.144.184:8667
    empresas:
        SERVILABOR:
            php_exec: /opt/php71/bin/php

    novasoftapi:
        url: http://50.19.144.184:80