<?php


namespace App\Form;


use Craue\FormFlowBundle\Form\FormFlow;

class HvFlow extends FormFlow
{
    protected function loadStepsConfig()
    {
        return parent::loadStepsConfig(); // TODO: Change the autogenerated stub
    }

}