---
- hosts: local
  vars:
      empresa: servilabor

  tasks:
    - name: Local webpack
      include: "{{ playbook_dir }}/include/local-webpack.yml"
      when: webpack is defined

- hosts: servilaborhg
  environment:
      TMPDIR: "/home4/jguerrero/tmp"
      TMP: "/home4/jguerrero/tmp"

  vars:
      empresa: servilabor
      empresa2: pta
      owner: jguerrero
      group: jguerrero
      php_exec: "/opt/php71/bin/php"
      composer: /opt/cpanel/composer/bin/composer
      release_console_path: "{{ ansistrano_release_path.stdout }}/bin/console"
      release_var_path: "{{ ansistrano_release_path.stdout }}/var"
      release_public_path: "{{ ansistrano_release_path.stdout }}/public"

      ansistrano_deploy_to: "/home4/jguerrero/sel2"

      ansistrano_shared_paths:
          - var/log
          - var/uploads

      ansistrano_keep_releases: 3

      ansistrano_deploy_via: git
      ansistrano_git_repo: git@github.com:diezsiete/sel.git
      ansistrano_git_branch: master
      ansistrano_git_identity_key_path: "{{ playbook_dir }}/id_rsa"
      #ansistrano_git_identity_key_remote_path: "{{ ansistrano_deploy_to }}/../.ssh/github_rsa"

      ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/deploy/after-symlink-shared2.yml"



  vars_files:
      - ./vars/deploy_vault_{{ empresa }}.yml
      - ./vars/deploy_vars.yml

  roles:
      - ansistrano.deploy


- hosts: local
  vars:
      empresa: servilabor
  tasks:
      - name: Remove archive webpack
        file:
            path: "{{ playbook_dir }}/../public/build.tgz"
            state: absent
        when: webpack is defined

      - name: yarn dev build assets
        command: yarn build-assets
        when: webpack is defined
        environment:
            EMPRESA: "{{ empresa }}"

      - name: yarn dev build
        command: yarn encore dev
        when: webpack is defined
        environment:
            EMPRESA: "{{ empresa }}"