---
- hosts: ptagd

  vars_files:
      - ./vars/deploy_vault.yml
      - ./vars/deploy_vars.yml

  vars:
      release_console_path: "{{ ansistrano_release_path.stdout }}/bin/console"
      release_var_path: "{{ ansistrano_release_path.stdout }}/var"

      ansistrano_deploy_to: "/home/ptaweb/sel2"
      ansistrano_deploy_via: git
      ansistrano_git_repo: git@github.com:diezsiete/sel.git
      ansistrano_git_branch: master
      ansistrano_git_identity_key_path: "{{ playbook_dir }}/id_rsa"

      ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/deploy/after-symlink-shared.yml"

  roles:
    - ansistrano.deploy