---
- hosts: local
  vars:
      empresa: pta
  tasks:
      - name: Clear build folder
        shell: "rm -rf ../public/build/*"
        args:
            warn: no

      - name: Build webpack
        command: "yarn build"
        environment:
            EMPRESA: "{{ empresa }}"

      - name: Archive webpack
        archive:
            path: "{{ playbook_dir }}/../public/build"
            dest: "{{ playbook_dir }}/../public/build.tgz"

- hosts: ptagd

  vars_files:
      - ./vars/deploy_vault.yml
      - ./vars/deploy_vars.yml

  vars:
      release_console_path: "{{ ansistrano_release_path.stdout }}/bin/console"
      release_var_path: "{{ ansistrano_release_path.stdout }}/var"
      release_public_path: "{{ ansistrano_release_path.stdout }}/public"

      ansistrano_deploy_to: "/home/ptaweb/sel2"
      ansistrano_deploy_via: git
      ansistrano_git_repo: git@github.com:diezsiete/sel.git
      ansistrano_git_branch: master
      ansistrano_git_identity_key_path: "{{ playbook_dir }}/id_rsa"

      ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/deploy/after-symlink-shared.yml"

  roles:
    - ansistrano.deploy


- hosts: local
  tasks:
      - name: Remove archive webpack
        file:
            path: "{{ playbook_dir }}/../public/build.tgz"
            state: absent
      - name: yarn dev build assets
        command: yarn build-assets
      - name: yarn dev build
        command: yarn encore dev