---
- hosts: local
  vars:
      empresa: servilabor

  tasks:
      - name: Local webpack
        include: "{{ playbook_dir }}/include/local-webpack.yml"
        when: webpack is defined

      - name: Archive blog images
        archive:
          path: "{{ playbook_dir }}/../public/img"
          dest: "{{ playbook_dir }}/../public/img.tgz"
        when: empresa == "pta"

- hosts: ptagd

  vars:
      empresa: servilabor
      empresa2: pta
      owner: ptaweb
      group: ptaweb
      php_exec: php
      composer: /opt/cpanel/composer/bin/composer
      release_console_path: "{{ ansistrano_release_path.stdout }}/bin/console"
      release_var_path: "{{ ansistrano_release_path.stdout }}/var"
      release_public_path: "{{ ansistrano_release_path.stdout }}/public"

      ansistrano_deploy_to: "/home/ptaweb/sel3"

      ansistrano_shared_paths:
          - var/log
          - var/uploads

      ansistrano_keep_releases: 3

      ansistrano_deploy_via: git
      ansistrano_git_repo: git@github.com:diezsiete/sel.git
      ansistrano_git_branch: master
      ansistrano_git_identity_key_path: "{{ playbook_dir }}/id_rsa"

      ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/deploy/after-symlink-shared.yml"

  vars_files:
      - ./vars/deploy_vault_{{ empresa }}_in_pta.yml
      - ./vars/deploy_vars.yml

  roles:
    - ansistrano.deploy


- hosts: local
  vars:
      empresa: servilabor
  tasks:
      - name: Remove archive webpack
        file:
            path: "{{ playbook_dir }}/../public/build.tgz"
            state: absent
        when: webpack is defined

      - name: Remove archive images
        file:
            path: "{{ playbook_dir }}/../public/img.tgz"
            state: absent

      - name: yarn dev build assets
        command: yarn build-assets
        when: webpack is defined
        environment:
            EMPRESA: "{{ empresa }}"

      - name: yarn dev build
        command: yarn encore dev
        when: webpack is defined
        environment:
            EMPRESA: "{{ empresa }}"