---
- hosts: local
  vars:
      empresa: pta

  tasks:
      - name: Archive blog images
        archive:
          path: "{{ playbook_dir }}/../public/img"
          dest: "{{ playbook_dir }}/../public/img.tgz"
        when: empresa == "pta"

- hosts: ptagd

  vars:
      empresa: pta
      empresa2: servilabor
      owner: ptaweb
      group: ptaweb
      php_exec: php
      composer: /opt/cpanel/composer/bin/composer
      release_console_path: "{{ ansistrano_release_path.stdout }}/bin/console"
      release_var_path: "{{ ansistrano_release_path.stdout }}/var"
      release_public_path: "{{ ansistrano_release_path.stdout }}/public"

      ansistrano_deploy_to: "/home/ptaweb/sel2"

      ansistrano_shared_paths:
          - var/log
          - var/uploads

      ansistrano_keep_releases: 3

      ansistrano_deploy_via: git
      ansistrano_git_repo: git@github.com:diezsiete/sel.git
      ansistrano_git_branch: master
      ansistrano_git_identity_key_path: "{{ playbook_dir }}/id_rsa"

      ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/deploy/after-symlink-shared.yml"

  vars_files:
      - ./vars/deploy_vault_{{ empresa }}.yml
      - ./vars/deploy_vars.yml

  roles:
    - ansistrano.deploy


- hosts: local
  vars:
      empresa: pta
  tasks:
      - name: Remove archive images
        file:
            path: "{{ playbook_dir }}/../public/img.tgz"
            state: absent